name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  project-name:
    description: The name of the project
    default: "Deploy"
    required: true
  owner:
    description: The owner of the repository
    default: ${{ github.repository_owner }}
    required: true
  repo:
    description: The repository name
    default: ${{ github.repository }}
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
