name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  date:
    description: 'Date to run the workflow'
    required: false
    default: 'Tomorrow at noon'
  wait-ms:
    description: 'Milliseconds to wait'
    required: false
    default: 0
  wait-delay-ms:
    description: 'Milliseconds to wait between checks on the schedule'
    required: false
    default: 20000
  workflow:
    description: 'Workflow to run at schedule time'
    required: false
  ref:
    description: 'Branch to run the workflow on'
    required: false
    default:  ${{ github.ref }}
  owner:
    description: 'Optional repository owner to run the workflow on.'
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: 'Optional repository name to run the workflow on.'
    default: ${{ github.repository }}
    required: false
  timezone:
    description: 'Timezone to use for the schedule'
    required: false
    default: 'EST'
  inputs:
    description: 'Inputs to pass to the workflow'
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
