name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  date:
    description: 'Date to run the workflow'
    required: false
    default: '2024-05-11'
  waitMs:
    description: 'Milliseconds to wait'
    required: false
    default: 0

runs:
  using: "node20"
  main: "dist/index.js"
