name: Schedule Workflow
author: Austen Stone
description: Schedule a workflow to run at a specific time
branding:
  icon: "calendar"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  workflow:
    description: 'Workflow to run at schedule time'
    required: true
  date:
    description: 'Date to run the workflow'
    required: false
    default: ${{ github.event.inputs.date }}
  wait-ms:
    description: 'Milliseconds to wait'
    required: false
    default: 0
  wait-delay-ms:
    description: 'Milliseconds to wait between checks on the schedule'
    required: false
    default: 20000
  ref:
    description: 'Branch to run the workflow on'
    required: false
    default:  ${{ github.ref }}
  owner:
    description: 'Optional repository owner to run the workflow on.'
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: 'Optional repository name to run the workflow on.'
    default: ${{ github.repository }}
    required: false
  timezone:
    description: 'Timezone to use for the schedule'
    required: false
    default: 'US/Eastern'
  inputs:
    description: 'Inputs to pass to the workflow'
    default: ${{ toJson(github.event.inputs) }}
    required: false
  inputs-ignore:
    description: 'Inputs to ignore when passing to the workflow'
    default: 'date,workflow'
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
