name: Basic

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: false
        default: 'Bob the Builder'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, ${{ github.event.inputs.name }}!
      - name: Run a multi-line script
        run: |
          git branch -a