name: Auto Update Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN || secrets.GITHUB_TOKEN }}

      - run: npx npm-check-updates -u --target minor
      - run: npm i --legacy-peer-deps
      - run: npm audit fix || true
      - run: npm run build

      - uses: stefanzweifel/git-auto-commit-action@v5
