name: Schedule Workflow Dispatch
on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: '2024-05-11'

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: check
        with:
          github-token: ${{ secrets.TOKEN }}
          date: ${{ github.event.inputs.date }}
          wait-ms: 300000
          workflow: 'basic.yml'
          timezone: 'EST'
