name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: '2024-05-11'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
      - uses: actions/checkout@v4
      - run: gh variable list
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
      - run: gh variable set MYVARIABLE --body "$ENV_VALUE"
        env:
          ENV_VALUE: "my value"
          GH_TOKEN: ${{ secrets.TOKEN }}
      - uses: ./
        with:
          github-token: ${{ secrets.TOKEN }}