name: 📅 Schedule Workflow Dispatch
on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: 'in 1 hour'
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'Mona the Octocat'
concurrency:
  group: schedule${{ github.event.inputs.date }}
  cancel-in-progress: true

jobs:
  schedule:
    name: 📅 Schedule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: check
        with:
          github-token: ${{ secrets.TOKEN }}
          date: ${{ github.event.inputs.date }}
          workflow: 'basic.yml'
          timezone: 'EST'
          inputs: ${{ toJson(inputs) }}
          wait-ms: 1000
          wait-delay-ms: 600000
