name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github-token: ${{ secrets.TOKEN }}