name: Schedule
on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: '2024-05-11'

jobs:
  set-variable:
    if: github.event.inputs.date
    runs-on: ubuntu-latest
    steps:
      - run: gh variable set Schedule_${{ github.event.inputs.date }} --body "${{ github.ref }}"
        env:
          ENV_VALUE: "my value"
          GH_TOKEN: ${{ secrets.TOKEN }}
  check-schedule:
    if: github.event.inputs.date == ''
    outputs:
      result: ${{ steps.check.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: check
        with:
          github-token: ${{ secrets.TOKEN }}
          date: 5/10/2024
  run:
    needs: check-schedule
    if: needs.check-schedule.outputs.result == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"