name: 📅 Schedule Workflow Dispatch
on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: 'in 1 hour'
      workflow:
        description: 'Workflow to run at schedule time'
        required: true
        type: choice
        options:
          - 'basic.yml'
          - 'codeql.yml'
concurrency:
  group: schedule${{ github.event.inputs.date }}
  cancel-in-progress: true

jobs:
  schedule:
    name: 📅 Schedule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          workflow: ${{ inputs.workflow }}
          inputs: ${{ toJson(inputs)}}
          inputs-ignore: date,workflow
