name: Schedule
on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: '2024-05-11'

jobs:
  check-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh variable set Schedule_${{ github.event.inputs.date }} --body "${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - uses: ./
        id: check
        with:
          github-token: ${{ secrets.TOKEN }}
          date: 5/14/2024
          wait-ms: 5000
  run:
    needs: check-schedule
    if: ${{ needs.check-schedule.outputs.result == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is scheduled!"
